import os
import win32com.client as client

text = """
This sample document is generated by WdBibTeX.

Some text with dummy umlaut \\cite{Umlaut} is[1].
The list of bibliography is placed to the thebibliography command as follows:

\\thebibliography

"""

ap = client.Dispatch('Word.Application')
ap.Visible = True

dc = ap.Documents.Add()
sl = ap.Selection
sl.InsertBefore(text)

dc.SaveAs2(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        'sample.docx'
    )
)

# Close document
dc.Close()

# Quit Word application if no other opened document
if len(ap.Documents) == 0:
    ap.Quit()
