import os
import win32com.client as client

text = """
This sample document is generated by WdBibTeX.

Sample citation\\cite{enArticle1}.
英語文献の引用例\\cite{enArticle1}。
Multiple citations example\\cite{enArticle2,enArticle3,enArticle4}.
複数文献の引用例\\cite{enArticle2,enArticle3,enArticle4}。
Examples of Japanese reference\\cite{jpArticle2,jpArticle3}.
日本語文献の引用例\\cite{jpArticle2,jpArticle3}。
The list of bibliography is placed to the thebibliography command as follows:
文献リストは以下の通りとなる。

\\thebibliography

"""

ap = client.Dispatch('Word.Application')
ap.Visible = True

dc = ap.Documents.Add()
sl = ap.Selection
sl.InsertBefore(text)

dc.SaveAs2(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        'sample.docx'
    )
)

# Close document
dc.Close()

# Quit Word application if no other opened document
if len(ap.Documents) == 0:
    ap.Quit()
