import os
import wdbibtex
import win32com.client as client

text = """
This sample document is generated by WdBibTeX version %s.

Some text with dummy citation \\cite{enArticle1} will be converted \
to [1] by executing wdbibtex.
The list of bibliography is placed to the thebibliography command as follows:

\\thebibliography

""" % wdbibtex.__version__

ap = client.Dispatch('Word.Application')
ap.Visible = True

dc = ap.Documents.Add()
sl = ap.Selection
sl.InsertBefore(text)

dc.SaveAs2(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        'sample.docx'
    )
)

# Close document
dc.Close()

# Quit Word application if no other opened document
if len(ap.Documents) == 0:
    ap.Quit()
