import os
import win32com.client as client

text = """
This sample document is generated by WdBibTeX.

WdBibTeX can (partially) parse preamble contents written between
"\\+begin{preamble}" and "\\+end{preamble}".
The preamble contents are removed in the latex-processed docx artifacts.
For citation package, some options are available to control citation style.
In this example, citation package is added with "superscript" option.
The "citeleft" and "citeright" is also modified.

Sample citation customization \\cite{enArticle1}.
Multiple citations example \\cite{enArticle2,enArticle3,enArticle4}.
The list of bibliography is placed to the thebibliography command as follows:

\\begin{preamble}
\\documentclass[10pt]{article}
\\usepackage[superscript]{cite}
\\renewcommand\\citeleft{(}
\\renewcommand\\citeright{)}
\\bibliographystyle{IEEEtran}
\\end{preamble}
\\thebibliography

"""

ap = client.Dispatch('Word.Application')
ap.Visible = True

dc = ap.Documents.Add()
sl = ap.Selection
sl.InsertBefore(text)

dc.SaveAs2(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        'sample.docx'
    )
)

# Close document
dc.Close()

# Quit Word application if no other opened document
if len(ap.Documents) == 0:
    ap.Quit()
